"""add subscription_tier to users

Revision ID: 2a353962963c
Revises: 629c230b0ebb
Create Date: 2026-02-26 17:12:40.959758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a353962963c'
down_revision: Union[str, None] = '629c230b0ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_pg = bind.dialect.name == 'postgresql'
    from sqlalchemy import inspect
    insp = inspect(bind)
    existing_tables = set(insp.get_table_names())

    if 'risk_weight_configs' not in existing_tables:
        op.create_table('risk_weight_configs',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('weights_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_risk_weight_configs_is_active'), 'risk_weight_configs', ['is_active'], unique=False)
        op.create_index(op.f('ix_risk_weight_configs_version'), 'risk_weight_configs', ['version'], unique=True)
        existing_tables.add('risk_weight_configs')

    if 'scoring_configs' not in existing_tables:
        op.create_table('scoring_configs',
    sa.Column('engine_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('weights_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_scoring_configs_engine_name'), 'scoring_configs', ['engine_name'], unique=False)
        op.create_index(op.f('ix_scoring_configs_is_active'), 'scoring_configs', ['is_active'], unique=False)
        op.create_index(op.f('ix_scoring_configs_version'), 'scoring_configs', ['version'], unique=False)
        existing_tables.add('scoring_configs')

    if 'risk_assessment_snapshots' not in existing_tables:
        op.create_table('risk_assessment_snapshots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timeline_id', sa.UUID(), nullable=True),
    sa.Column('scoring_version', sa.String(length=50), nullable=False),
    sa.Column('config_version', sa.String(length=50), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('contributing_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold_breaches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weight_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['committed_timelines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_risk_assessment_snapshots_config_version'), 'risk_assessment_snapshots', ['config_version'], unique=False)
        op.create_index(op.f('ix_risk_assessment_snapshots_risk_level'), 'risk_assessment_snapshots', ['risk_level'], unique=False)
        op.create_index(op.f('ix_risk_assessment_snapshots_scoring_version'), 'risk_assessment_snapshots', ['scoring_version'], unique=False)
        op.create_index(op.f('ix_risk_assessment_snapshots_timeline_id'), 'risk_assessment_snapshots', ['timeline_id'], unique=False)
        op.create_index(op.f('ix_risk_assessment_snapshots_user_id'), 'risk_assessment_snapshots', ['user_id'], unique=False)

    if 'longitudinal_events' in existing_tables:
        op.drop_index('ix_longitudinal_events_entity_id', table_name='longitudinal_events')
        op.drop_index('ix_longitudinal_events_entity_type', table_name='longitudinal_events')
        op.drop_index('ix_longitudinal_events_event_type', table_name='longitudinal_events')
        op.drop_index('ix_longitudinal_events_role', table_name='longitudinal_events')
        op.drop_index('ix_longitudinal_events_source_module', table_name='longitudinal_events')
        op.drop_index('ix_longitudinal_events_user_id', table_name='longitudinal_events')
        op.drop_table('longitudinal_events')
    # Create PostgreSQL enum types before altering columns
    progress_event_type_enum = sa.Enum(
        'MILESTONE_COMPLETED', 'MILESTONE_DELAYED', 'STAGE_STARTED',
        'STAGE_COMPLETED', 'ACHIEVEMENT', 'BLOCKER', 'UPDATE',
        name='progress_event_type',
    )
    user_role_enum = sa.Enum(
        'RESEARCHER', 'SUPERVISOR', 'INSTITUTIONAL_ADMIN',
        name='user_role',
    )
    subscription_tier_enum = sa.Enum(
        'FREE', 'TEAM', 'INSTITUTIONAL',
        name='subscription_tier',
    )
    if is_pg:
        progress_event_type_enum.create(bind, checkfirst=True)
        user_role_enum.create(bind, checkfirst=True)
        subscription_tier_enum.create(bind, checkfirst=True)

    op.alter_column('progress_events', 'event_type',
               existing_type=sa.VARCHAR(),
               type_=progress_event_type_enum,
               existing_nullable=False,
               postgresql_using='event_type::text::progress_event_type')
    op.alter_column('progress_events', 'event_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # Change tags from varchar to varchar[] so GIN index is valid (skip if already array from 20260219_0004)
    if is_pg:
        op.execute("""
            DO $$ DECLARE t text;
            BEGIN
                SELECT format_type(atttypid, atttypmod) INTO t FROM pg_attribute
                WHERE attrelid = 'progress_events'::regclass AND attname = 'tags' AND not attisdropped;
                IF t IS NOT NULL AND t NOT LIKE '%%[]' THEN
                    ALTER TABLE progress_events ALTER COLUMN tags TYPE varchar[] USING ARRAY[]::varchar[];
                END IF;
            END $$;
        """)
    progress_event_indexes = {idx['name'] for idx in insp.get_indexes('progress_events')}
    if 'ix_progress_events_tags_gin' not in progress_event_indexes:
        op.create_index('ix_progress_events_tags_gin', 'progress_events', ['tags'], unique=False, postgresql_using='gin')
    if is_pg:
        op.execute('ALTER TABLE users ALTER COLUMN role DROP DEFAULT')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=user_role_enum,
               existing_nullable=False,
               postgresql_using='role::text::user_role')
    if is_pg:
        op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'researcher'::user_role")
    # Fill NULL subscription_tier values before applying NOT NULL constraint
    op.execute("UPDATE users SET subscription_tier = 'free' WHERE subscription_tier IS NULL")
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(),
               type_=subscription_tier_enum,
               nullable=False,
               postgresql_using='subscription_tier::text::subscription_tier')
    user_indexes = {idx['name'] for idx in insp.get_indexes('users')}
    if 'ix_users_subscription_tier' not in user_indexes:
        op.create_index(op.f('ix_users_subscription_tier'), 'users', ['subscription_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_pg = bind.dialect.name == 'postgresql'

    op.drop_index(op.f('ix_users_subscription_tier'), table_name='users')
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.Enum('FREE', 'TEAM', 'INSTITUTIONAL', name='subscription_tier'),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='subscription_tier::text')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('RESEARCHER', 'SUPERVISOR', 'INSTITUTIONAL_ADMIN', name='user_role'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='role::text')
    op.drop_index('ix_progress_events_tags_gin', table_name='progress_events', postgresql_using='gin')
    op.execute('ALTER TABLE progress_events ALTER COLUMN tags TYPE varchar USING NULL')
    op.alter_column('progress_events', 'event_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('progress_events', 'event_type',
               existing_type=sa.Enum('MILESTONE_COMPLETED', 'MILESTONE_DELAYED', 'STAGE_STARTED', 'STAGE_COMPLETED', 'ACHIEVEMENT', 'BLOCKER', 'UPDATE', name='progress_event_type'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='event_type::text')
    if is_pg:
        sa.Enum(name='progress_event_type').drop(bind, checkfirst=True)
        sa.Enum(name='user_role').drop(bind, checkfirst=True)
        sa.Enum(name='subscription_tier').drop(bind, checkfirst=True)
    op.create_table('longitudinal_events',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('source_module', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('event_id', name='longitudinal_events_pkey'),
    comment='Append-only event log; do not update or delete rows.'
    )
    op.create_index('ix_longitudinal_events_user_id', 'longitudinal_events', ['user_id'], unique=False)
    op.create_index('ix_longitudinal_events_source_module', 'longitudinal_events', ['source_module'], unique=False)
    op.create_index('ix_longitudinal_events_role', 'longitudinal_events', ['role'], unique=False)
    op.create_index('ix_longitudinal_events_event_type', 'longitudinal_events', ['event_type'], unique=False)
    op.create_index('ix_longitudinal_events_entity_type', 'longitudinal_events', ['entity_type'], unique=False)
    op.create_index('ix_longitudinal_events_entity_id', 'longitudinal_events', ['entity_id'], unique=False)
    op.drop_index(op.f('ix_risk_assessment_snapshots_user_id'), table_name='risk_assessment_snapshots')
    op.drop_index(op.f('ix_risk_assessment_snapshots_timeline_id'), table_name='risk_assessment_snapshots')
    op.drop_index(op.f('ix_risk_assessment_snapshots_scoring_version'), table_name='risk_assessment_snapshots')
    op.drop_index(op.f('ix_risk_assessment_snapshots_risk_level'), table_name='risk_assessment_snapshots')
    op.drop_index(op.f('ix_risk_assessment_snapshots_config_version'), table_name='risk_assessment_snapshots')
    op.drop_table('risk_assessment_snapshots')
    op.drop_index(op.f('ix_scoring_configs_version'), table_name='scoring_configs')
    op.drop_index(op.f('ix_scoring_configs_is_active'), table_name='scoring_configs')
    op.drop_index(op.f('ix_scoring_configs_engine_name'), table_name='scoring_configs')
    op.drop_table('scoring_configs')
    op.drop_index(op.f('ix_risk_weight_configs_version'), table_name='risk_weight_configs')
    op.drop_index(op.f('ix_risk_weight_configs_is_active'), table_name='risk_weight_configs')
    op.drop_table('risk_weight_configs')
    # ### end Alembic commands ###
